name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  equatable: ^2.0.5
  mockito: ^5.4.2
  build_runner: ^2.4.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dio: ^5.4.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  rxdart: ^0.27.7
  bloc_test: ^9.1.5
  geolocator: ^10.1.0
  lottie: ^2.7.0
  go_router: ^12.1.1
  permission_handler: ^11.0.1
  geocoding: ^2.1.1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  adaptive_theme: ^3.4.1
  gap: ^3.0.1
  flutter_svg: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/technologies/
